blueprint:
  name: Presence Actions
  description: 'Run a set of actions when someone arrives. Run another set when they
    leave.'
  domain: script
  input:
    tgt_lights:
      name: Target Lights
      description: The lights to set to full brightness
      selector:
        entity:
          domain: light
    brightness:
      name: Target Brightness
      description: Custom value used as "full brightness. Defaults to 100%"
      default: 100
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: "%"
          step: 1
          mode: slider
  #source_url: https://github.com/dbeltman/hass-blueprints/blob/master/presence-actions.yaml
sequence:
  - service: light.turn_on
    target:
      entity_id: !input tgt_lights
    data:
      brightness_pct: !input brightness
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: light.turn_on
    target:
      entity_id: !input tgt_lights
    data:
      xy_color:
        - 0.443
        - 0.379
      transition: 3
mode: single
icon: mdi:sun-wireless-outline